# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"trace": "decorators.ipynb"}

modules = ["decorators.py"]

doc_url = "https://Hevia.github.io/copperhead/"

git_url = "https://github.com/Hevia/copperhead/tree/main/"

def custom_doc_links(name): return None
